name = "tbg"
version = "0.1.0"
license = "MIT"
author = "Qian-Sheng Shi"
maintainer = "shiqsh@qq.com"
copyright = "Copyright 2026, Qian-Sheng Shi"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"

[dependencies]
stdlib = "*"
openmp = "*"
blas = "*"

